---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  project: default
  sources:
    - repoURL: docker.io/envoyproxy
      chart: gateway-helm
      targetRevision: "v1.9.2"
      helm:
        releaseName: envoy-gateway
        valueFiles:
          - $values/argocd/apps/envoy-gateway/values.yaml
    - repoURL: https://github.com/jimdaga/dagalab-infra.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: envoy-gateway-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
