apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard
  namespace: {{ .Release.Namespace }}
spec:
  secretName: wildcard-tls
  issuerRef:
    kind: ClusterIssuer
    name: {{ .Values.certificate.issuer }}
  dnsNames:
    - {{ .Values.domain | quote }}
    - {{ printf "*.%s" .Values.domain | quote }}
