apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        type: LoadBalancer
        {{- with .Values.gateway.loadBalancerIP }}
        annotations:
          metallb.io/loadBalancerIPs: {{ . }}
        {{- end }}
