apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault
spec:
  provider:
    vault:
      server: {{ .Values.vault.server }}
      path: {{ .Values.vault.kvPath }}
      version: v2
      auth:
        kubernetes:
          mountPath: {{ .Values.vault.authMountPath }}
          role: {{ .Values.vault.role }}
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
