{{- range .Values.externalSecrets }}
{{- if ne .enabled false }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: {{ .name }}
    {{- with .template }}
    template:
      data:
        {{- toYaml . | nindent 8 }}
    {{- end }}
  data:
    {{- range .data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .key }}
        property: {{ .property }}
    {{- end }}
{{- end }}
{{- end }}
