name: validate

on:
  pull_request:
  push:
    branches: [main]

jobs:
  helm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: azure/setup-helm@v4
      - name: Lint local charts
        run: make lint
      - name: Template local charts
        run: make template > /dev/null
